### ISSUE TITLE
Can I put a link to your project in Webcam Capture README?

### ISSUE THREAD

**Issue by sarxos** [frankpapenmeier/webcam-capture-driver-native#1]
Hello @frankpapenmeier,

Congratulations on your awesome work using Webcam Capture API to build capture driver which uses Windows Media Foundation instead of DirectShow.

I was thinking to do it already in 2013 (https://github.com/sarxos/webcam-capture/issues/151) but due to my work duties I had no time to implement this on my own. Therefore, what you did is really great and I'm sure community will gain from it :)

I would like to put a link to your project (with appropriate credits and description) from within the Webcam Capture project main page. I hope you don't mind?

**Comment by frankpapenmeier** [comment]
Hi sarxos,
yes, you are welcome to link to this project.
I very much like your Java webcam capture project too and use it within the desktop port of our baby monitor app available at http://www.babyphonemobile.com ... Because users complained about issues on Windows 8 tablets, I started this project and decided to share it back to the community. If you ever encounter any issues or have any ideas on improving this capture driver, you are welcome to share your ideas.
