### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by monochromata** [frankpapenmeier/webcam-capture-driver-native#6]
I'd like to use this library under Linux. Do you think it is possible to build it under Linux, too?

Thanks!

**Comment by frankpapenmeier** [comment]
Sorry for the late response. I was not notified about your message (or must have missed it) and just stumbled across it.

In theory, this should be possible because the video capture library by roxlu claims to also provide linux support. Unfortunately, I am currently not developing on linux and thus cannot test it. However, if you would ever provide a PR, I would look into it.
